import 'package:studeo/src/features/common/domain/enums/enums.dart';
import 'package:studeo/src/features/common/domain/models/models.dart';

abstract class Constants {
  static const na = 'N/A';
  static const Duration kAnimationDuration = Duration(milliseconds: 200);

  /// Languages map
  static const languagesMap = {
    AppLanguageType.english: LanguageModel('en', 'US'),
  };
}

const root = 'https://roaakdm.com';
const imagesDirectory = 'flutter-gallery-example/hd';

const List<String> images = [
  '$root/$imagesDirectory/paris-01.jpeg',
  '$root/$imagesDirectory/paris-02.jpeg',
  '$root/$imagesDirectory/paris-03.jpeg',
  '$root/$imagesDirectory/paris-04.jpeg',
  '$root/$imagesDirectory/paris-05.jpeg',
  '$root/$imagesDirectory/paris-06.jpeg',
  '$root/$imagesDirectory/paris-07.jpeg',
  '$root/$imagesDirectory/paris-08.jpeg',
  '$root/$imagesDirectory/paris-09.jpeg',
  '$root/$imagesDirectory/paris-10.jpeg',
  '$root/$imagesDirectory/paris-11.jpeg',
  '$root/$imagesDirectory/paris-12.jpeg',
  '$root/$imagesDirectory/paris-13.jpeg',
  '$root/$imagesDirectory/paris-14.jpeg',
  '$root/$imagesDirectory/paris-15.jpeg',
  '$root/$imagesDirectory/paris-16.jpeg',
  '$root/$imagesDirectory/paris-17.jpeg',
  '$root/$imagesDirectory/paris-18.jpeg',
  '$root/$imagesDirectory/paris-19.jpeg',
  '$root/$imagesDirectory/paris-20.jpeg',
  '$root/$imagesDirectory/paris-21.jpeg',
  '$root/$imagesDirectory/paris-22.jpeg',
  '$root/$imagesDirectory/paris-23.jpeg',
  '$root/$imagesDirectory/paris-24.jpeg',
  '$root/$imagesDirectory/paris-25.jpeg',
  '$root/$imagesDirectory/florence-01.jpeg',
  '$root/$imagesDirectory/florence-02.jpeg',
  '$root/$imagesDirectory/florence-03.jpeg',
  '$root/$imagesDirectory/florence-04.jpeg',
  '$root/$imagesDirectory/florence-05.jpeg',
  '$root/$imagesDirectory/florence-06.jpeg',
  '$root/$imagesDirectory/florence-07.jpeg',
  '$root/$imagesDirectory/florence-08.jpeg',
  '$root/$imagesDirectory/florence-09.jpeg',
  '$root/$imagesDirectory/florence-10.jpeg',
  '$root/$imagesDirectory/florence-11.jpeg',
  '$root/$imagesDirectory/florence-12.jpeg',
  '$root/$imagesDirectory/florence-13.jpeg',
  '$root/$imagesDirectory/florence-14.jpeg',
  '$root/$imagesDirectory/florence-15.jpeg',


  '$root/$imagesDirectory/paris-01.jpeg',
  '$root/$imagesDirectory/paris-02.jpeg',
  '$root/$imagesDirectory/paris-03.jpeg',
  '$root/$imagesDirectory/paris-04.jpeg',
  '$root/$imagesDirectory/paris-05.jpeg',
  '$root/$imagesDirectory/paris-06.jpeg',
  '$root/$imagesDirectory/paris-07.jpeg',
  '$root/$imagesDirectory/paris-08.jpeg',
  '$root/$imagesDirectory/paris-09.jpeg',
  '$root/$imagesDirectory/paris-10.jpeg',
  '$root/$imagesDirectory/paris-11.jpeg',
  '$root/$imagesDirectory/paris-12.jpeg',
  '$root/$imagesDirectory/paris-13.jpeg',
  '$root/$imagesDirectory/paris-14.jpeg',
  '$root/$imagesDirectory/paris-15.jpeg',
  '$root/$imagesDirectory/paris-16.jpeg',
  '$root/$imagesDirectory/paris-17.jpeg',
  '$root/$imagesDirectory/paris-18.jpeg',
  '$root/$imagesDirectory/paris-19.jpeg',
  '$root/$imagesDirectory/paris-20.jpeg',
  '$root/$imagesDirectory/paris-21.jpeg',
  '$root/$imagesDirectory/paris-22.jpeg',
  '$root/$imagesDirectory/paris-23.jpeg',
  '$root/$imagesDirectory/paris-24.jpeg',
  '$root/$imagesDirectory/paris-25.jpeg',
  '$root/$imagesDirectory/florence-01.jpeg',
  '$root/$imagesDirectory/florence-02.jpeg',
  '$root/$imagesDirectory/florence-03.jpeg',
  '$root/$imagesDirectory/florence-04.jpeg',
  '$root/$imagesDirectory/florence-05.jpeg',
  '$root/$imagesDirectory/florence-06.jpeg',
  '$root/$imagesDirectory/florence-07.jpeg',
  '$root/$imagesDirectory/florence-08.jpeg',
  '$root/$imagesDirectory/florence-09.jpeg',
  '$root/$imagesDirectory/florence-10.jpeg',
  '$root/$imagesDirectory/florence-11.jpeg',
  '$root/$imagesDirectory/florence-12.jpeg',
  '$root/$imagesDirectory/florence-13.jpeg',
  '$root/$imagesDirectory/florence-14.jpeg',
  '$root/$imagesDirectory/florence-15.jpeg',
];
